fn main() {
    // Tauri 2.11.2+：remote 内容（主窗口导航到的 http://127.0.0.1:*/）默认无法调用应用命令，
    // 必须显式声明 AppManifest 命令清单，tauri-build 才会生成 allow-/deny- 权限文件
    // （写入 ./permissions/autogenerated/），再由 capabilities/main.json 引用。
    // 清单必须与 main.rs 的 generate_handler! 保持一致。
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "retry_start",
            "open_model_guide",
            "get_model_status",
        ]),
    ))
    .expect("tauri-build 失败");
}
