on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      GIT_AUTHOR_NAME: ReSerendipity
      GIT_AUTHOR_EMAIL: zengyangc@outlook.com
      GIT_COMMITTER_NAME: ReSerendipity
      GIT_COMMITTER_EMAIL: zengyangc@outlook.com
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-pull-request: true
